package com.mycompany.time_table_management_system.db.model;
// Generated Aug 2, 2015 2:18:56 PM by Hibernate Tools 3.6.0




/**
 * Classroom generated by hbm2java
 */
@SuppressWarnings("serial")
public class Classroom  implements java.io.Serializable {


     private String classroomId;
     private Building building;
     private String classroomName;
     private Integer classroomSize;

    public Classroom() {
    }

	
    public Classroom(String classroomId) {
        this.classroomId = classroomId;
    }
    public Classroom(String classroomId, Building building, String classroomName, Integer classroomSize) {
       this.classroomId = classroomId;
       this.building = building;
       this.classroomName = classroomName;
       this.classroomSize = classroomSize;
    }
   
    public String getClassroomId() {
        return this.classroomId;
    }
    
    public void setClassroomId(String classroomId) {
        this.classroomId = classroomId;
    }
    public Building getBuilding() {
        return this.building;
    }
    
    public void setBuilding(Building building) {
        this.building = building;
    }
    public String getClassroomName() {
        return this.classroomName;
    }
    
    public void setClassroomName(String classroomName) {
        this.classroomName = classroomName;
    }
    public Integer getClassroomSize() {
        return this.classroomSize;
    }
    
    public void setClassroomSize(Integer classroomSize) {
        this.classroomSize = classroomSize;
    }


}


