package com.mycompany.time_table_management_system.db.model;
// Generated Aug 2, 2015 2:18:56 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Department generated by hbm2java
 */
public class Department  implements java.io.Serializable {


     private String departmentId;
     private Building building;
     private String departmentName;
     private Set lecturers = new HashSet(0);
     private Set equipments = new HashSet(0);
     private Set schedules = new HashSet(0);
     private Set modules = new HashSet(0);

    public Department() {
    }

	
    public Department(String departmentId) {
        this.departmentId = departmentId;
    }
    public Department(String departmentId, Building building, String departmentName, Set lecturers, Set equipments, Set schedules, Set modules) {
       this.departmentId = departmentId;
       this.building = building;
       this.departmentName = departmentName;
       this.lecturers = lecturers;
       this.equipments = equipments;
       this.schedules = schedules;
       this.modules = modules;
    }
   
    public String getDepartmentId() {
        return this.departmentId;
    }
    
    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId;
    }
    public Building getBuilding() {
        return this.building;
    }
    
    public void setBuilding(Building building) {
        this.building = building;
    }
    public String getDepartmentName() {
        return this.departmentName;
    }
    
    public void setDepartmentName(String departmentName) {
        this.departmentName = departmentName;
    }
    public Set getLecturers() {
        return this.lecturers;
    }
    
    public void setLecturers(Set lecturers) {
        this.lecturers = lecturers;
    }
    public Set getEquipments() {
        return this.equipments;
    }
    
    public void setEquipments(Set equipments) {
        this.equipments = equipments;
    }
    public Set getSchedules() {
        return this.schedules;
    }
    
    public void setSchedules(Set schedules) {
        this.schedules = schedules;
    }
    public Set getModules() {
        return this.modules;
    }
    
    public void setModules(Set modules) {
        this.modules = modules;
    }




}


