package com.mycompany.time_table_management_system.db.model;
// Generated Aug 2, 2015 2:18:56 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;

/**
 * Equipment generated by hbm2java
 */
public class Equipment  implements java.io.Serializable {


     private EquipmentId id;
     private Department department;
     private String discription;
     private BigDecimal equipmentValue;
     private String equipmentType;

    public Equipment() {
    }

	
    public Equipment(EquipmentId id, Department department) {
        this.id = id;
        this.department = department;
    }
    public Equipment(EquipmentId id, Department department, String discription, BigDecimal equipmentValue, String equipmentType) {
       this.id = id;
       this.department = department;
       this.discription = discription;
       this.equipmentValue = equipmentValue;
       this.equipmentType = equipmentType;
    }
   
    public EquipmentId getId() {
        return this.id;
    }
    
    public void setId(EquipmentId id) {
        this.id = id;
    }
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }
    public String getDiscription() {
        return this.discription;
    }
    
    public void setDiscription(String discription) {
        this.discription = discription;
    }
    public BigDecimal getEquipmentValue() {
        return this.equipmentValue;
    }
    
    public void setEquipmentValue(BigDecimal equipmentValue) {
        this.equipmentValue = equipmentValue;
    }
    public String getEquipmentType() {
        return this.equipmentType;
    }
    
    public void setEquipmentType(String equipmentType) {
        this.equipmentType = equipmentType;
    }




}


