package com.mycompany.time_table_management_system.db.model;
// Generated Aug 2, 2015 2:18:56 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Lecturer generated by hbm2java
 */
public class Lecturer  implements java.io.Serializable {


     private String lecturerId;
     private Department department;
     private String lecturerName;
     private String contactNo;
     private String email;
     private Set schedules = new HashSet(0);

    public Lecturer() {
    }

	
    public Lecturer(String lecturerId, Department department) {
        this.lecturerId = lecturerId;
        this.department = department;
    }
    public Lecturer(String lecturerId, Department department, String lecturerName, String contactNo, String email, Set schedules) {
       this.lecturerId = lecturerId;
       this.department = department;
       this.lecturerName = lecturerName;
       this.contactNo = contactNo;
       this.email = email;
       this.schedules = schedules;
    }
   
    public String getLecturerId() {
        return this.lecturerId;
    }
    
    public void setLecturerId(String lecturerId) {
        this.lecturerId = lecturerId;
    }
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }
    public String getLecturerName() {
        return this.lecturerName;
    }
    
    public void setLecturerName(String lecturerName) {
        this.lecturerName = lecturerName;
    }
    public String getContactNo() {
        return this.contactNo;
    }
    
    public void setContactNo(String contactNo) {
        this.contactNo = contactNo;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getSchedules() {
        return this.schedules;
    }
    
    public void setSchedules(Set schedules) {
        this.schedules = schedules;
    }




}


