package com.mycompany.time_table_management_system.db.model;
// Generated Aug 2, 2015 2:18:56 PM by Hibernate Tools 3.6.0


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Module generated by hbm2java
 */
public class Module  implements java.io.Serializable {


     private String moduleNo;
     private String departmentId;
     private String moduleTitle;
     private double credit;
     private boolean isGpa;
     private int lectureHours;
     private int practicalHours;

    public Module() {
    }

	
    public Module(String moduleNo, String departmentId, String moduleTitle) {
        this.moduleNo = moduleNo;
        this.departmentId = departmentId;
        this.moduleTitle = moduleTitle;
    }
    public Module(String moduleNo, String departmentId, String moduleTitle, double credit, boolean isGpa, int lectureHours, int practicalHours) {
       this.moduleNo = moduleNo;
       this.departmentId = departmentId;
       this.moduleTitle = moduleTitle;
       this.credit = credit;
       this.isGpa = isGpa;
       this.lectureHours = lectureHours;
       this.practicalHours = practicalHours;
    }
   
    public String getModuleNo() {
        return this.moduleNo;
    }
    
    public void setModuleNo(String moduleNo) {
        this.moduleNo = moduleNo;
    }
    public String getDepartmentId() {
        return this.departmentId;
    }
    
    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId;
    }
    public String getModuleTitle() {
        return this.moduleTitle;
    }
    
    public void setModuleTitle(String moduleTitle) {
        this.moduleTitle = moduleTitle;
    }
    public double getCredit() {
        return this.credit;
    }
    
    public void setCredit(double credit) {
        this.credit = credit;
    }
    public Boolean getIsGpa() {
        return this.isGpa;
    }
    
    public void setIsGpa(Boolean isGpa) {
        this.isGpa = isGpa;
    }
    public int getLectureHours() {
        return this.lectureHours;
    }
    
    public void setLectureHours(int lectureHours) {
        this.lectureHours = lectureHours;
    }
    public int getPracticalHours() {
        return this.practicalHours;
    }
    
    public void setPracticalHours(int practicalHours) {
        this.practicalHours = practicalHours;
    }


	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((moduleNo == null) ? 0 : moduleNo.hashCode());
		return result;
	}


	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Module other = (Module) obj;
		if (moduleNo == null) {
			if (other.moduleNo != null)
				return false;
		} else if (!moduleNo.equals(other.moduleNo))
			return false;
		return true;
	}
    
    




}


