package com.mycompany.time_table_management_system.db.model;
// Generated Aug 2, 2015 2:18:56 PM by Hibernate Tools 3.6.0



/**
 * ScheduleId generated by hbm2java
 */
public class ScheduleId  implements java.io.Serializable {


     private int timePeriod;
     private String day;
     private String moduleNo;
     private String classroomId;
     private String departmentId;

    public ScheduleId() {
    }

    public ScheduleId(int timePeriod, String day, String moduleNo, String classroomId, String departmentId) {
       this.timePeriod = timePeriod;
       this.day = day;
       this.moduleNo = moduleNo;
       this.classroomId = classroomId;
       this.departmentId = departmentId;
    }
   
    public int getTimePeriod() {
        return this.timePeriod;
    }
    
    public void setTimePeriod(int timePeriod) {
        this.timePeriod = timePeriod;
    }
    public String getDay() {
        return this.day;
    }
    
    public void setDay(String day) {
        this.day = day;
    }
    public String getModuleNo() {
        return this.moduleNo;
    }
    
    public void setModuleNo(String moduleNo) {
        this.moduleNo = moduleNo;
    }
    public String getClassroomId() {
        return this.classroomId;
    }
    
    public void setClassroomId(String classroomId) {
        this.classroomId = classroomId;
    }
    public String getDepartmentId() {
        return this.departmentId;
    }
    
    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ScheduleId) ) return false;
		 ScheduleId castOther = ( ScheduleId ) other; 
         
		 return (this.getTimePeriod()==castOther.getTimePeriod())
 && ( (this.getDay()==castOther.getDay()) || ( this.getDay()!=null && castOther.getDay()!=null && this.getDay().equals(castOther.getDay()) ) )
 && ( (this.getModuleNo()==castOther.getModuleNo()) || ( this.getModuleNo()!=null && castOther.getModuleNo()!=null && this.getModuleNo().equals(castOther.getModuleNo()) ) )
 && ( (this.getClassroomId()==castOther.getClassroomId()) || ( this.getClassroomId()!=null && castOther.getClassroomId()!=null && this.getClassroomId().equals(castOther.getClassroomId()) ) )
 && ( (this.getDepartmentId()==castOther.getDepartmentId()) || ( this.getDepartmentId()!=null && castOther.getDepartmentId()!=null && this.getDepartmentId().equals(castOther.getDepartmentId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getTimePeriod();
         result = 37 * result + ( getDay() == null ? 0 : this.getDay().hashCode() );
         result = 37 * result + ( getModuleNo() == null ? 0 : this.getModuleNo().hashCode() );
         result = 37 * result + ( getClassroomId() == null ? 0 : this.getClassroomId().hashCode() );
         result = 37 * result + ( getDepartmentId() == null ? 0 : this.getDepartmentId().hashCode() );
         return result;
   }   


}


