package com.mycompany.time_table_management_system.db.model;
// Generated Aug 2, 2015 2:18:56 PM by Hibernate Tools 3.6.0



import java.util.List;


/**
 * Schedule generated by hbm2java
 */
public class Schedule  implements java.io.Serializable {


	 /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int timePeriod;
     private int day;
     private String moduleNo;
     private String classroomId;
     private String departmentId;
     private String batchNo; 
     private String semester;
     private List<Lecturer> lecturerList;

    public Schedule() {
    }

	
    public Schedule(int timePeriod, int day, String moduleNo, String classroomId, String departmentId,String batchNo,String semester) {
        this.timePeriod = timePeriod;
        this.day = day;
        this.moduleNo = moduleNo;
        this.classroomId = classroomId;
        this.departmentId = departmentId;
        this.batchNo=batchNo;
        this.semester=semester;
     }
    
    
    
   
    public Schedule(int timePeriod, int day, String moduleNo, String classroomId, String departmentId,String batchNo,String semester,
			List<Lecturer> lecturerList) {
		super();
		this.timePeriod = timePeriod;
		this.day = day;
		this.moduleNo = moduleNo;
		this.classroomId = classroomId;
		this.departmentId = departmentId;
		this.batchNo=batchNo;
        this.semester=semester;
		this.lecturerList = lecturerList;
	}


	public int getTimePeriod() {
        return this.timePeriod;
    }
    
    public void setTimePeriod(int timePeriod) {
        this.timePeriod = timePeriod;
    }
    public int getDay() {
        return this.day;
    }
    
    public void setDay(int day) {
        this.day = day;
    }
    public String getModuleNo() {
        return this.moduleNo;
    }
    
    public void setModuleNo(String moduleNo) {
        this.moduleNo = moduleNo;
    }
    public String getClassroomId() {
        return this.classroomId;
    }
    
    public void setClassroomId(String classroomId) {
        this.classroomId = classroomId;
    }
    public String getDepartmentId() {
        return this.departmentId;
    }
    
    public void setDepartmentId(String departmentId) {
        this.departmentId = departmentId;
    }
    

	public String getBatchNo() {
		return batchNo;
	}


	public void setBatchNo(String batchNo) {
		this.batchNo = batchNo;
	}


	public String getSemester() {
		return semester;
	}


	public void setSemester(String semester) {
		this.semester = semester;
	}


	public List<Lecturer> getLecturerList() {
		return lecturerList;
	}


	public void setLecturerList(List<Lecturer> lecturerList) {
		this.lecturerList = lecturerList;
	}


	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((moduleNo == null) ? 0 : moduleNo.hashCode());
		return result;
	}


	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Schedule other = (Schedule) obj;
		if (moduleNo == null) {
			if (other.moduleNo != null)
				return false;
		} else if (!moduleNo.equals(other.moduleNo))
			return false;
		return true;
	}



    

}


