package com.mycompany.time_table_management_system.db.model;
// Generated Aug 2, 2015 2:18:56 PM by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Schedule generated by hbm2java
 */
public class Schedule  implements java.io.Serializable {


     private ScheduleId id;
     private Module module;
     private Classroom classroom;
     private Department department;
     private Set lecturers = new HashSet(0);

    public Schedule() {
    }

	
    public Schedule(ScheduleId id, Module module, Classroom classroom, Department department) {
        this.id = id;
        this.module = module;
        this.classroom = classroom;
        this.department = department;
    }
    public Schedule(ScheduleId id, Module module, Classroom classroom, Department department, Set lecturers) {
       this.id = id;
       this.module = module;
       this.classroom = classroom;
       this.department = department;
       this.lecturers = lecturers;
    }
   
    public ScheduleId getId() {
        return this.id;
    }
    
    public void setId(ScheduleId id) {
        this.id = id;
    }
    public Module getModule() {
        return this.module;
    }
    
    public void setModule(Module module) {
        this.module = module;
    }
    public Classroom getClassroom() {
        return this.classroom;
    }
    
    public void setClassroom(Classroom classroom) {
        this.classroom = classroom;
    }
    public Department getDepartment() {
        return this.department;
    }
    
    public void setDepartment(Department department) {
        this.department = department;
    }
    public Set getLecturers() {
        return this.lecturers;
    }
    
    public void setLecturers(Set lecturers) {
        this.lecturers = lecturers;
    }




}


